# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r
dist: trusty
sudo: false

cache:
  packages: true

warnings_are_errors: true

r_packages:
  - covr

matrix:
  include:
    - env:
      - SPARK_VERSION="1.6.3"
      - JAVA_VERSION=openjdk7
    - env:
      - SPARK_VERSION="2.2.1"
      - JAVA_VERSION=oraclejdk8
    - env:
      - SPARK_VERSION="2.3.1"
      - JAVA_VERSION=openjdk8
    - env:
      - LIVY_VERSION="0.5.0"
      - JAVA_VERSION=openjdk8

before_install:
  - jdk_switcher use $JAVA_VERSION
  - echo $JAVA_HOME

script:
  - |
    R CMD build .
    export SPARKLYR_LOG_FILE=/tmp/sparklyr.log
    if [[ $SPARK_VERSION == "2.3.0" ]]; then
      R CMD check --no-build-vignettes --no-manual --no-tests sparklyr*tar.gz
      travis_wait 45 Rscript .travis.R --coverage
    else
      travis_wait 35 R CMD check --no-build-vignettes --no-manual sparklyr*tar.gz
    fi

after_failure:
  - |
    grep -B 10 -A 20 ERROR /tmp/sparklyr.log
    cd tests
    export NOT_CRAN=true
    travis_wait 35 Rscript ../.travis.R --testthat
    sleep 2
