# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r
sudo: false
cache: packages
warnings_are_errors: true

jdk:
  - oraclejdk8

r_packages:
  - covr

env:
  - SPARK_VERSION="1.6.3"
  - SPARK_VERSION="2.2.0"

script:
  - |
    R CMD build .
    R CMD check --no-build-vignettes --no-manual --no-tests sparklyr*tar.gz
    export SPARKLYR_LOG_FILE=/tmp/sparklyr.log
    [[ $SPARK_VERSION == "2.2.0" ]] && travis_wait 30 Rscript -e 'covr::codecov()'
    [[ $SPARK_VERSION != "2.2.0" ]] && travis_wait 30 Rscript ../.travis.R

after_failure:
  - |
    tail -n 500 /tmp/sparklyr.log
    cd tests
    export NOT_CRAN=true
    travis_wait 30 Rscript ../.travis.R
    sleep 2
