# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r
sudo: false
cache: packages
jdk:
  - oraclejdk8
r_github_packages:
  - jimhester/covr
after-success:
  - Rscript -e 'covr::codecov()'
