# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r
dist: trusty
sudo: false

branches:
  only:
    - master

cache:
  packages: true

warnings_are_errors: true

matrix:
  include:
    - name: "Arrow (R release, oraclejdk8)"
      r: release
      env:
        - R_ARROW="true"
        - JAVA_VERSION=oraclejdk8

before_install:
  - jdk_switcher use $JAVA_VERSION
  - echo $JAVA_HOME
  - if [[ $R_ARROW == "true" ]]; then Rscript .travis.R --arrow; fi

script:
  - |
    R CMD build .
    export SPARKLYR_LOG_FILE=/tmp/sparklyr.log
    R CMD check --no-build-vignettes --no-manual --no-tests sparklyr*tar.gz

    if [[ $CODE_COVERAGE == "true" ]]; then
      Rscript .travis.R --coverage
    else
      Rscript .travis.R --testthat
    fi
  - chmod +x ./ci/arrow.sh
  - "./ci/arrow.sh"

after_failure:
  - |
    grep -B 10 -A 20 ERROR /tmp/sparklyr.log
