# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r
dist: trusty
sudo: false

branches:
  only:
    - master

cache:
  packages: true

warnings_are_errors: true

r_packages:
  - covr

matrix:
  include:
    - name: "Spark 1.6.3 (R 3.2, openjdk7)"
      r: 3.2
      env:
        - SPARK_VERSION="1.6.3"
        - JAVA_VERSION=openjdk7
    - name: "Spark 2.2.1 (R oldrel, oraclejdk8)"
      r: oldrel
      env:
        - SPARK_VERSION="2.2.1"
        - JAVA_VERSION=oraclejdk8
    - name: "Spark 2.3.2 (R release, openjdk8)"
      r: release
      env:
        - SPARK_VERSION="2.3.2"
        - JAVA_VERSION=openjdk8
    - name: "Livy 0.5.0 (R release, openjdk8)"
      r: release
      env:
        - LIVY_VERSION="0.5.0"
        - JAVA_VERSION=openjdk8
    - name: "Arrow (R release, openjdk8)"
      r: release
      env:
        - R_ARROW="true"
        - JAVA_VERSION=openjdk8

before_install:
  - jdk_switcher use $JAVA_VERSION
  - echo $JAVA_HOME
  - |
    if [[ R_ARROW == "true" ]]; then
      sudo apt install -y -V apt-transport-https
      sudo apt install -y -V lsb-release
      sudo wget -O /usr/share/keyrings/red-data-tools-keyring.gpg https://packages.red-data-tools.org/$(lsb_release --id --short | tr 'A-Z' 'a-z')/red-data-tools-keyring.gpg
      sudo tee /etc/apt/sources.list.d/red-data-tools.list <<APT_LINE
      deb [signed-by=/usr/share/keyrings/red-data-tools-keyring.gpg] https://packages.red-data-tools.org/$(lsb_release --id --short | tr 'A-Z' 'a-z')/ $(lsb_release --codename --short) universe
      deb-src [signed-by=/usr/share/keyrings/red-data-tools-keyring.gpg] https://packages.red-data-tools.org/$(lsb_release --id --short | tr 'A-Z' 'a-z')/ $(lsb_release --codename --short) universe
      APT_LINE
      sudo apt update
      sudo apt install -y -V libarrow-dev # For C++
      sudo apt install -y -V libarrow-glib-dev # For GLib (C)
    fi
  - Rscript .travis.R --arrow

script:
  - |
    R CMD build .
    export SPARKLYR_LOG_FILE=/tmp/sparklyr.log
    if [[ $SPARK_VERSION == "2.3.0" ]]; then
      R CMD check --no-build-vignettes --no-manual --no-tests sparklyr*tar.gz
      travis_wait 45 Rscript .travis.R --coverage
    else
      travis_wait 35 R CMD check --no-build-vignettes --no-manual sparklyr*tar.gz
    fi

after_failure:
  - |
    grep -B 10 -A 20 ERROR /tmp/sparklyr.log
    cd tests
    export NOT_CRAN=true
    travis_wait 35 Rscript ../.travis.R --testthat
    sleep 2
