# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r
sudo: false
cache: packages
jdk:
  - oraclejdk8
r_packages:
  - covr
script:
  - |
    R CMD build .
    export SPARKLYR_LOG_FILE=/tmp/sparklyr.log
    travis_wait 30 R CMD check --no-build-vignettes --no-manual sparklyr*tar.gz
after_success:
  - |
    travis_wait 30 Rscript -e 'covr::codecov()'
after_failure:
  - |
    tail -n 500 /tmp/sparklyr.log
    sleep 2
