# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r
sudo: false
cache: packages
jdk:
  - oraclejdk8
r_packages:
  - covr
script:
  - |
    R CMD build .
    R CMD check --no-build-vignettes --no-manual --no-tests sparklyr*tar.gz
    travis_wait 20 Rscript -e 'covr::codecov()'
after_failure:
  - find /tmp/Rtmp* -name "*_spark.log" -exec cat {} \;
