# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r
sudo: false
cache: packages
jdk:
  - oraclejdk8
r_packages:
  - covr
script:
  - |
    R CMD build .
    travis_wait 20 R CMD check --no-build-vignettes --no-manual sparklyr*tar.gz
after_success:
  - Rscript -e 'covr::codecov()'
